from time import sleep
from personaje import Personaje

primo_beso = False
fin_juego = False
nom_ligue = "null"
lester = None  # Se inicializa desde el main

def intro():
    print("\nEsta es una historia de cuatro amigos, Lester, Dax, Hugh y Zohan\n")
    sleep(1)
    print("Son cuatro chicos de 19 años, quienes se conocen desde la secundaria\n")
    sleep(1)
    print("En la noche de año nuevo, Zohan se acordo de algo que le dijo Lester\n")
    sleep(1)
    print("Una promesa, que tiene que cumplir en el presente año\n")
    sleep(1)
    print("Por lo que rapidamente, Zohan toma su celular y decide hablar en el chat grupal de los amigos\n")
    sleep(1)
    print("\n                  1 de Enero de 2015 - 12:30 am - Chat Grupal                     \n")
    sleep(1)
    print("Zohan: @todos")
    sleep(1)
    print("Zohan: Tengo un anuncio importante que dar")
    sleep(1)
    print("Dax: ¿Que Paso?")
    sleep(1)
    print("Dax: Me estaba durmiendo")
    sleep(1)
    print("Zohan: Me acordé de algo de suma importancia")
    sleep(1)
    print("Zohan: Es que no se si hacerlo más al rato")
    sleep(1)
    print("Zohan: Porque necesito especialmente a Lester disponible")
    sleep(1)
    print("Lester: Aqui estoy")
    sleep(1)
    print("Lester: Dilo de una vez")
    sleep(1)
    print("Zohan: Okey")
    sleep(1)
    print("Zohan: @todos")
    sleep(1)
    print("Zohan: Primero que nada")
    sleep(1)
    print("Zohan: Feliz 2015")
    sleep(1)
    print("Zohan: Ya es 2015")
    sleep(1)
    print("Zohan: Y quiero hacerle un amable recordatorio a mi amigo Lester")
    sleep(1)
    print("Zohan: Ya que dijo que haría algo especial este año")
    sleep(1)
    print("Hugh: Al fin sacaras a Lester del Grupo?")
    sleep(1)
    print("Zohan: Nop")
    sleep(1)
    print("Zohan: Mi buen amigo Lester comento algo el 16 de agosto de 2013 a las 7:43 pm")
    sleep(1)
    print("Zohan: y cito")
    sleep(1)
    print("\n                 16 de Agosto de 2013 - 19:43 pm - Chat Grupal                   \n")
    sleep(1)
    print("Lester: Aunque claro aún tengo presente el plan por si no doy mi primer beso antes de los 20")
    sleep(1)
    print("Lester: Ir a una convención")
    sleep(1)
    print("Lester: Ver a una cosplayer de chica anime")
    sleep(1)
    print("Lester: y ofrecerle unos $2000 para que me de un beso")
    sleep(1)
    print("Lester: con todo respeto")
    sleep(1)
    print("\n                  1 de Enero de 2015 - 01:00 am - Chat Grupal                    \n")
    sleep(1)
    print("Dax: XD")
    sleep(1)
    print("Dax: Ya se por donde va esto")
    sleep(1)
    print("Zohan: Tic Tac Lester Tic Tac")
    sleep(1)
    print("Lester: Se cancela ")
    sleep(1)
    print("Lester: Ni siquiera recordaba haber dicho eso")
    sleep(1)
    print("Hugh: XD")
    sleep(1)
    print("Hugh: Eres un reverendo pendejo Lester")
    sleep(1)
    print("Zohan: No Lester")
    sleep(1)
    print("Zohan: Ya no hay vuelta atrás")
    sleep(1)
    print("Zohan: Te quedan 50 días Lester")
    sleep(1)
    print("Zohan: Lo que quedaba de 2013 no hiciste nada")
    sleep(1)
    print("Zohan: y en 2014 tampoco")
    sleep(1)
    print("Zohan: Y ya solo te quedan menos de 2 meses Lester")
    sleep(1)
    print("Zohan: El tiempo corre")
    sleep(1)
    print("\nLester cumple 20 años dentro de 50 dias\n")
    sleep(1)
    print("Asi que como dijo Zohan\n")
    sleep(1)
    print("EL TIEMPO CORRE\n")

def bad_ending():
    global fin_juego
    sleep(1)
    print("\n                        Unos Meses Despues                   \n")
    sleep(1)
    print("\n             14 de Marzo de 2015 - 16:00 pm - Super Geek Fest                     \n")
    sleep(1)
    print("Zohan: Muy bien")
    sleep(1)
    print("Zohan: Ya llegamos al Super Geek Fest")
    sleep(1)
    print("Zohan: ¿Estas Listo Lester?")
    sleep(1)
    print("Lester: MmMmMmMmM")
    sleep(1)
    print("\nVes nerviosamente a Hugh a quien le importas un comino pero ahi esta\n")
    sleep(1)
    print("Luego ves nerviosamente a Dax quien trato de ayudarte pero fallo estrepitosamente\n")
    sleep(1)
    print("Ves que ambos te estan mirando de una manera bastante peculiar, como si estuviaran aguantando la respiración\n")
    sleep(1)
    print("Lester: Chicos ¿Le Decimos?")
    sleep(1)
    print("Zohan: Decirme que")
    sleep(1)
    print("Lester: Te sere sincero Zohan")
    sleep(1)
    print("Lester: No alcanze a ahorrar $2000 para pagarle a la cosplayer")
    sleep(1)
    print("\nVes que Hugh y Dax se empiezan a reír fuertemente\n")
    sleep(1)
    print("Zohan: ¡PUTA MADRE LESTER!\n")
    fin_juego = True

def norm_ending():
    global primer_beso, fin_juego
    sleep(1)
    print("\n                        Unos Meses Despues                   \n")
    sleep(1)
    print("\n             14 de Marzo de 2015 - 16:00 pm - Super Geek Fest                     \n")
    sleep(1)
    print("Zohan: Muy bien")
    sleep(1)
    print("Zohan: Ya llegamos al Super Geek Fest")
    sleep(1)
    print("Zohan: ¿Estas Listo Lester?")
    sleep(1)
    print("Lester: Eso Creo")
    sleep(1)
    print("Zohan: Okey, En base a este mapa, estamos en el centro y")
    sleep(1)
    print("Zohan: ¡AY CARAJO!")
    sleep(1)
    print("Zohan: ¡SON UN MONTON DE COSPLAYERS!")
    sleep(1)
    print("Dax: Es una convención, genio")
    sleep(1)
    print("Zohan: Lo sé pero va a estar dificíl econtrar a una cosplayer de chica anime")
    sleep(1)
    print("Hugh: Lo que tenemos que hacer por el estupido de Lester")
    sleep(1)
    print("\n                        Unas Horas Despues                  \n")
    sleep(1)
    print("Zohan: Okey, esta es la Cosplayer No. 500 de chica anime")
    sleep(1)
    print("Zohan: Muy Bien Lester ya sabes que decir campeón")
    sleep(1)
    print("Lester: MmMmMmMmM")
    sleep(1)
    print("Lester: No lo se Zohan")
    sleep(1)
    print("Lester: Empiezo a creer que esto es una perdida de tiempo")
    sleep(1)
    print("\nVes lentamente como Zohan te da una cachetada\n")
    sleep(1)
    print("Lester: Auch")
    sleep(1)
    print("Zohan: Alivianate Bastardo")
    sleep(1)
    print("Zohan: Ya llegamos aquí y no tienes nada que perder¿si o no?")
    sleep(1)
    print("Dax: Si")
    sleep(1)
    print("Hugh: Va a perder o $2000 o su dignidad")
    sleep(1)
    print("Zohan: Callate Hugh")
    sleep(1)
    print("Zohan: Que dices Lester ¿Lo haras o eres un cobarde?")
    sleep(1)
    print("Lester: Esta bien")
    sleep(1)
    print("\nTe acercas lentamente a la cosplayer, estas congelado y no sabes que decir\n")
    sleep(1)
    print("Lester: MmMmMmMmM")
    sleep(1)
    print("Lester: Oye Amiga")
    sleep(1)
    print("Lester: MmMmMmMmM")
    sleep(1)
    print("Cosplayer de Chica Anime: ¿Que se te ofrece amigo?")
    sleep(1)
    print("Lester: MmMmMmMmM")
    sleep(1)
    print("Lester: No se si sea posible que me des unnnnn")
    sleep(1)
    print("Lester: MmMmMmMmM")
    sleep(1)
    print("Zohan: Carajo, Lester se trabó")
    sleep(1)
    print("Dax: Se le olvidaron todos los consejos que le di")
    sleep(1)
    print("Hugh: Que perdedor")
    sleep(1)
    print("Cosplayer de Chica Anime: ¿Un que?")
    sleep(1)
    print("Lester: U-un Beso a cambio d-de $2000")
    sleep(1)
    print("Cosplayer de Chica Anime: ...")
    sleep(5)
    print("\nEstas demasiado nervioso porque se esta tardando en responder\n")
    sleep(1)
    print("Cosplayer de Chica Anime: Va ¿Porqué no?")
    lester.resDinero(2000)
    primer_beso = True
    sleep(1)
    print("Zohan: Lo logró, ese bastardo lo logró")
    sleep(1)
    print("Dax: Parece que alguien se tiene que retractar por lo que dijo hace rato")
    sleep(1)
    print("Hugh: Por como lo hizo, no lo creo")
    sleep(1)
    print("\nEntraste en un extasís, al fin diste tu primer beso\n")
    sleep(1)
    print("Lester: ¡CHICOS! ¡LO LOGRE!\n")
    fin_juego = True

def novia_escena():
    global nom_ligue,primer_beso
    sleep(1)
    print("\n               En ese mismo momento                   \n")
    sleep(1)
    print(f"Lester: Oye {nom_ligue}")
    sleep(1)
    print(f"{nom_ligue}: Dime ¿Qué Ocurre?")
    sleep(1)
    print("Lester: Es que, bueno, tu sabes")
    sleep(1)
    print("Lester: Ya llevamos buen rato saliendo")
    sleep(1)
    print("Lester: y yo me preguntaba")
    sleep(1)
    print("Lester: ...")
    sleep(1)
    print("Lester: MmMmMmMmM")
    sleep(1)
    print("\nEstas congelado, tienes miedo, la incertidumbre te provoca inquietud\n")
    sleep(1)
    print(f"{nom_ligue}: Lester ¿Qué Pasa?")
    sleep(1)
    print(f"\nEscuchar la voz de {nom_ligue}, viendo su preocupación, te hace despertar\n")
    sleep(1)
    print(f"Lester: {nom_ligue}")
    sleep(1)
    print("Lester: ¿Quisieras ser mi novia?")
    sleep(1)
    print(f"{nom_ligue}: ...")
    sleep(5)
    print("\nEstas demasiado nervioso porque se esta tardando en responder\n")
    sleep(1)
    print(f"{nom_ligue}: Si")    
    sleep(1)
    print(f"{nom_ligue}: Si quiero ser tu novia")   
    sleep(1)
    print("\nNo lo puedes creer, lo lograste, quisieras que tus amigos estuvieran aqui para verlo \n")
    sleep(1)
    print(f"\nVes lentamente como {nom_ligue} se avalanza sobre ti\n")
    sleep(1)
    print("\nY\n")
    primer_beso = True
    sleep(1)
    print("\nEntraste en un extasís, al fin diste tu primer beso\n")
    sleep(1)
    print("Lester: (Wow)")
    sleep(1)
    print("Lester: (Lo Logré)\n")
    sleep(1)

def good_ending():
    global fin_juego,nom_ligue
    sleep(1)
    print("\n                        Un Año Despues                   \n")
    sleep(1)
    print(f"\nEstas apunto de celebrar el primer aniversario que estas junto a {nom_ligue}\n")
    sleep(1)
    print(f"{nom_ligue}: ¿Ya estas listo amor?")
    sleep(1)
    print("Lester: Si ¿y tú?")
    sleep(1)
    print(f"{nom_ligue}: Aun me falta maquillarme, esperame")
    sleep(1)
    print("Lester: Okey")
    sleep(1)
    print("\nDecides aprovechar el tiempo para hablar con tus amigos\n")
    sleep(1)
    print("Abres chat grupal que tienes con tus amigos\n")
    sleep(1)
    print(f"Lester: Bueno Chicos, hoy cumplo un año que estoy con {nom_ligue} y la verdad les quiero agradecer")
    sleep(1)
    print("Lester: Primero, Gracias Zohan, porque si no me hubieras puesto este absurdo reto")
    sleep(1)
    print("Lester: No hubiera conocido a una maravillosa persona")
    sleep(1)
    print("Zohan: De nada, para eso estamos Lester")
    sleep(1)
    print("Lester: Segundo, Gracias Dax, por apoyarme y darme consejos")
    sleep(1)
    print("Lester: Se que debi hacerte caso antes, pero al final si accedí y lo entendí todo")
    sleep(1)
    print("Dax: No hay nada que agradecer Lester, para eso estamos")
    sleep(1)
    print("Lester: y por ultimo gracias Hugh, se que no te importo, pero almenos estuviste ahi")
    sleep(1)
    print("Lester: y por eso te lo agradezco")
    sleep(1)
    print("Hugh: Okey")
    sleep(1)
    print("Lester: Bueno, ya me voy, gracias por todo chicos")
    sleep(1)
    print(f"\nTe desconectas para salir con {nom_ligue}\n")
    sleep(1)
    print("Zohan: Bro, realmente hicimos crecer a Lester")
    sleep(1)
    print("Dax: Y si, quien crería que Lester ya tiene novia")
    sleep(1)
    print("Hugh: Yo hubiera apostado mi casa a que moría virgen\n")
    fin_juego = True
